language: go

sudo: false

go:
- "1.10.x"

env:
  - DEP_VERSION="0.5.0"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - go get -v -u github.com/alecthomas/gometalinter/...  golang.org/x/tools/cmd/cover github.com/mattn/goveralls
  # -t is required because some tests have dependency that are not imported from project
  #- go get -v -t ./...
  - gometalinter --install

script:
  - go test -timeout 10s -v -covermode=count -coverprofile=coverage.out ./...
  - make
  - gometalinter --enable-all --disable=lll

after_script:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - rm -v jagozzi
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
