language: go

sudo: false

go:
- "1.10.x"

before_script:
  - go get -v -u  github.com/kardianos/govendor github.com/alecthomas/gometalinter/...  golang.org/x/tools/cmd/cover github.com/mattn/goveralls
  - govendor sync -v
  # -t is required because some tests have dependency that are not imported from project
  - go get -v -t ./...
  - gometalinter --install

script:
  - go test -timeout 10s -v -covermode=count -coverprofile=coverage.out ./...
  - make
  - gometalinter --enable-all --disable=lll

after_script:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - rm -v jagozzi
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
