language: go

go:
- "1.10.x"

before_script:
  - go get -t -v ./...

script:
  - make test
  - make

after_script:
  - go get -v github.com/alecthomas/gometalinter/...
  - gometalinter --install
  - gometalinter --enable-all --disable=lll

after_success:
  - rm -v jagozzi
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
