language: go

go:
- "1.10.x"

before_script:
  - go get -t -v ./...
  - go get -v github.com/alecthomas/gometalinter/...
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls
  - gometalinter --install

script:
  - go test -timeout 5s -v -covermode=count -coverprofile=coverage.out ./...
  - make
  - gometalinter --enable-all --disable=lll

after_script:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - rm -v jagozzi
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
