language: go

go:
- "1.10.x"

after_script:
  - go get -v github.com/alecthomas/gometalinter/...
  - gometalinter --install
  - gometalinter

after_success:
  - rm -v jagozzi
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
